config/routes.rb
Rails.application.routes.draw do

  get "homes/index"

  controller :keywords, as: 'keywords', path: 'keywords' do
    get '/', to: "keywords#index"
    post 'search'
  end

  controller :authorizations, as: 'authorizations' do
    get "login"
    get "callback"
    get "logout"
  end

  controller :accounts, as: 'accounts', path: 'accounts' do
    get "/", to: "accounts#index"
    put "select"
  end

  root :to => "homes#index"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def index
    @selected_account = selected_account
    @accounts = {"Test Account" => '352-051-7337'}
  end

  def select
    if params[:account][:id].present?
      self.selected_account = params[:account][:id]
      flash[:notice] = "Selected account: %s" % selected_account
      redirect_to keywords_path
    else
      flash[:error] = "Please select a valid account before proceeding"
      redirect_to accounts_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate

  # Returns the API version in use.
    def get_api_version()
      return TargetingIdeaService.api_version
    end

    # Returns currently selected account.
    def selected_account
      @selected_account ||= session[:selected_account]
      return @selected_account
    end

    # Sets current account to the specified one.
    def selected_account=(new_selected_account)
      @selected_account = new_selected_account
      session[:selected_account] = @selected_account
    end

    # Checks if we have a valid credentials.
    def authenticate()
      token = session[:token]
      redirect_to authorizations_login_path if token.nil?
      return !token.nil?
    end

    # Returns an API object.
    def get_adwords_api
      @api ||= create_adwords_api()
      return @api
    end

    # Creates an instance of AdWords API class. Uses a configuration file and
    # Rails config directory.
    def create_adwords_api()
      @api = AdwordsApi::Api.new({
              :authentication => {
                :method => 'OAuth2',
                :oauth2_client_id => ENV.fetch("OAUTH2_CLIENT_ID") ,
                :oauth2_client_secret => ENV.fetch("OAUTH2_CLIENT_SECRET"),
                :developer_token => ENV.fetch("DEVELOPER_TOKEN"),
                :user_agent => ""
              },
              :service => {
                :environment => 'PRODUCTION'
              }
            })

      token = session[:token]
      # If we have an OAuth2 token in session we use the credentials from it.
      if token
        credentials = @api.credential_handler()
        credentials.set_credential(:oauth2_token, token)
        credentials.set_credential(:client_customer_id, selected_account)
      end
      return @api
    end
end

app/controllers/authorizations_controller.rb
class AuthorizationsController < ApplicationController

  skip_before_action :authenticate

  GOOGLE_LOGOUT_URL = 'https://www.google.com/accounts/Logout'

  def login
    api = get_adwords_api

    if session[:token]
      redirect_to keywords_path
    else
      begin
        token = api.authorize({:oauth2_callback => authorizations_callback_url})
      rescue AdsCommon::Errors::OAuth2VerificationRequired => e
        @login_url = e.oauth_url
      end
    end
  end

  def callback
    api = get_adwords_api
    begin
      session[:token] = api.authorize(
        {
          :oauth2_callback => authorizations_callback_url,
          :oauth2_verification_code => params[:code]
        }
      )
      flash.notice = 'Authorized successfully'
      redirect_to accounts_path
    rescue AdsCommon::Errors::OAuth2VerificationRequired => e
      flash.alert = 'Authorization failed'
      redirect_to authorizations_login_path
    end
  end

  def logout
    [:selected_account, :token].each {|key| session.delete(key)}
    redirect_to GOOGLE_LOGOUT_URL
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  skip_before_filter :authenticate

  def index
  end
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_result, only: [ :index, :search ]

  def index
  end

  def search
    api = get_adwords_api
    targeting_idea_service = TargetingIdeaService.new(
      api,
      keywords:  search_params[:search],
      locations: search_params[:locations]
    )

    if targeting_idea_service.valid?
      @result = TargetingIdeas.new(targeting_idea_service.fetch).all
      flash.now[:success] = "Search completed successfully"
    else
      flash.now[:error] = targeting_idea_service.errors.full_messages.join("<br/>").html_safe
    end

    render :index
  end

private

  def search_params
    params.require(:keywords).permit(:search, :locations).tap do |object|
      object[:locations] = [ Country.find_by_code(object[:locations]).try(:id) ]
      object[:search] = [ object[:search] ]
    end
  end

  def set_result
    @result = []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.fetch(flash_type.to_sym) { flash_type.to_s }
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} alert-dismissible", role: 'alert') do
        concat(content_tag(:button, class: 'close', data: { dismiss: 'alert' }) do
          concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
          concat content_tag(:span, 'Close', class: 'sr-only')
        end)
        concat message
      end)
    end
    nil
  end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
  def country_codes
    Country.list_with_names_and_codes
  end
end

app/views/accounts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-push-3">
      <h2>Select an account Before continue</h2>
      <%= form_tag accounts_select_path, method: :put, class: "form-horizontal" do %>
        <div class="form-group">
          <label for="select-account" class="col-md-2 control-label">Select Account:</label>
          <div class="col-md-5">
            <%=
              select_tag "account[id]",
                options_for_select(@accounts),
                prompt: "Select an Account",
                class: "form-control",
                id: "select-account"
            %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-5">
            <button type="submit" class="btn btn-primary">Continue</button>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/authorizations/login.html.erb
<h1>Authorization required</h1>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
<% end %>

<p>Please authorize with a google account first:</p>

<p>
  <%= link_to @login_url.to_s do %>
    <%= icon('google', 'Login', id: 'g-authorize', class: 'fa-4x', "aria-hidden": true) %>
  <% end %>
</p>

app/views/homes/index.html.erb
<div class="container">
  <h1>Welcome to the AdWords on Keyword Search application</h1>
  <div class="col-md-6 col-md-push-4">
    <%= link_to authorizations_login_path do %>
       <%= icon('sign-in', 'Login', id: 'logIn', class: 'fa-4x', "aria-hidden": true) %>
    <% end %>
  </div>
</div>

app/views/keywords/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <%= form_tag keywords_search_path, class: "form-horizontal" do %>
        <div class="form-group">
          <label for="keywords-search" class="col-sm-2 control-label">Keyword</label>
          <div class="col-md-5">
            <%= text_field_tag "keywords[search]", "", class: "form-control", id: "keywords-search" %>
          </div>
        </div>
        <div class="form-group">
          <label for="country-id" class="col-md-2 control-label">Country</label>
          <div class="col-md-5">
            <%= select_tag "keywords[locations]", options_for_select(country_codes), prompt: "Select a location", class: "form-control", id: 'country-id' %>
          </div>
        </div>
        <div class="form-group">
          <div class="col-md-offset-2 col-md-5">
            <button type="submit" class="btn btn-primary">Search</button>
          </div>
        </div>
        <span id="helpBlock" class="help-block"><%= @result.count %> targeting ideas found.</span>
      <% end %>
    </div>
    <div class="col-md-6">
      <table class="table table-bordered keywords-search-volume">
        <thead>
          <tr class="active">
            <th>Keyword</td>
            <th>Search Volume</td>
          </th>
        </thead>
        <tbody>
          <% @result.each do |row| %>
            <tr>
              <td><%= row.keyword %></td>
              <td><%= row.search_volume %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KeywordSearch</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main">
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>